/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/invites` | `/invites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomDrawerContent`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/ErrorMessage`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingSpinner`; params?: Router.UnknownInputParams; } | { pathname: `/components/PasswordValidator`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/LoadingContext`; params?: Router.UnknownInputParams; } | { pathname: `/utils/validation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/group/[id]` | `/group/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/invites` | `/invites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AuthButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CustomDrawerContent`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CustomInput`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ErrorMessage`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LoadingSpinner`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PasswordValidator`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/context/LoadingContext`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/validation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/group/[id]` | `/group/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/invites${`?${string}` | `#${string}` | ''}` | `/invites${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/components/AuthButton${`?${string}` | `#${string}` | ''}` | `/components/CustomDrawerContent${`?${string}` | `#${string}` | ''}` | `/components/CustomInput${`?${string}` | `#${string}` | ''}` | `/components/ErrorMessage${`?${string}` | `#${string}` | ''}` | `/components/LoadingSpinner${`?${string}` | `#${string}` | ''}` | `/components/PasswordValidator${`?${string}` | `#${string}` | ''}` | `/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/context/LoadingContext${`?${string}` | `#${string}` | ''}` | `/utils/validation${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/invites` | `/invites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomDrawerContent`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/ErrorMessage`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingSpinner`; params?: Router.UnknownInputParams; } | { pathname: `/components/PasswordValidator`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/LoadingContext`; params?: Router.UnknownInputParams; } | { pathname: `/utils/validation`; params?: Router.UnknownInputParams; } | `${'/(app)'}/group/${Router.SingleRoutePart<T>}` | `/group/${Router.SingleRoutePart<T>}` | { pathname: `${'/(app)'}/group/[id]` | `/group/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
